language: python

os: linux
dist: bionic
python: 3.8
addons:
   apt:
      packages:
         - libblas-dev
         - liblapack-dev
         - gfortran-7
         - gfortran-8
         - python-pip

jobs:
   include:
      - name: meson-build
        env: FC=ifort CC=icc
        addons:
           apt:
              sources:
              - sourceline: 'deb https://apt.repos.intel.com/oneapi all main'
                key_url: 'https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB'
              packages:
              - intel-oneapi-ifort
              - intel-oneapi-icc
              - intel-oneapi-mkl
              - intel-oneapi-mkl-devel
              - intel-oneapi-openmp
        before_install:
        - source /opt/intel/inteloneapi/setvars.sh
        script:
        - meson build --buildtype=release --prefix=$PWD/install -Dla_backend=mkl-static
        - OMP_NUM_THREADS=2 ninja -C build test install
      - name: meson-build
        env: FC=gfortran-8 CC=gcc-8
        script:
        - meson build --buildtype=release --prefix=$PWD/install --warnlevel=0 -Dla_backend=netlib
        - OMP_NUM_THREADS=2 ninja -C build test install
      - name: meson-build
        env: FC=gfortran-7 CC=gcc-7
        script:
        - meson build --buildtype=release --prefix=$PWD/install --warnlevel=0 -Dla_backend=netlib
        - OMP_NUM_THREADS=2 ninja -C build test install
      - name: CMake-build
        env: FC=gfortran-8 CC=gcc-8
        script:
        - mkdir _build
        - cd _build
        - cmake -DCMAKE_INSTALL_PREFIX=$PWD/../install ..
        - OMP_NUM_THREADS=2 make -j all test install

install:
   - pip3 install meson ninja pytest numpy
